{{- if .Values.ingress.enabled }}
{{- $fullName := include "lior-nginx.fullname" . }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ printf "%s-route" $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . }}
    {{- else }}
    - web
    {{- end }}
  routes:
    {{- range .Values.ingress.hosts }}
    {{- $host := .host }}
    {{- range .paths }}
    - match: Host(`{{ $host }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $.Values.service.port }}
    {{- end }}
    {{- end }}
{{- end }}
