apiVersion: v1
kind: Service
metadata:
  name: {{ include "lior-nginx.fullname" . }}
  labels:
    {{- include "lior-nginx.labels" . | nindent 4 }}
spec:
  type: {{ include "lior-nginx.serviceType" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "lior-nginx.selectorLabels" . | nindent 4 }}
