replicaCount: 2

namespace: n

image:
  repository: liortal26/lior-nginx-frontend
  tag: latest
  pullPolicy: IfNotPresent

# pvc:
#   name: nginx-pvc
#   storage: 1Gi
#   storageClassName: local-storage
#   mountPath: /usr/share/nginx/html/data

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false
