apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lior-frontend-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 314525640319.dkr.ecr.il-central-1.amazonaws.com
    chart: lior/helm-charts/lior-nginx
    targetRevision: "0.1.3"
    helm:
      values: |
        replicaCount: 2

        image:
          repository: 314525640319.dkr.ecr.il-central-1.amazonaws.com/lior/helm/frontend
          tag: "20"
          pullPolicy: IfNotPresent


        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "traefik"
          hosts:
            - host: lior-ingress.aws.cts.care
              paths:
                - path: /
                  pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: lior

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

